<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_alobHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php
    $blockTabs     = $_alobHelper->getBlockTab();
    $attributeTabs = $_alobHelper->getAttributeTab();
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $content = ''; ?>
            <div class="items-tabs">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <!-- <div class="data item content" id="<?php /* @escapeNotVerified  echo $alias; */ ?>" data-role="content">
                    <?php /* @escapeNotVerified echo $html; */ ?>
                </div> -->

                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($blockTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled'])) {
                        continue;
                    }
                    $alias = $tab['block'];
                    $html  = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($alias)->toHtml();
                    if (!trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($attributeTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled']) ) {
                        continue;
                    }
                    $alias   = $tab['attribute'];
                    $blockAttribute = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Attributes');
                    $_product = $blockAttribute->getProduct();
                    $dataAttribute  = $blockAttribute->getAdditionalData();
                    $html = '';
                    if(isset($dataAttribute[$alias])) :
                        $_data = $dataAttribute[$alias];
                        $html .= '<table class="data table additional-attributes ' . $_data['code'] . '">';
                        $html .= '<tbody>';
                        $html .= '<tr>';
                        $html .=    '<th class="col label" scope="row">' . $block->escapeHtml($_data['label']) . '</th>';
                        $html .=    '<td class="col data" data-th="' . $block->escapeHtmlAttr($_data['label']) . '">' . $_helper->productAttribute($_product, $_data['value'], $_data['code']) . '</td>';
                        $html .= '</tr>';
                        $html .= '</tbody>';
                        $html .= '</table>';
                    else :
                        $attributeContent  = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getData($alias), $alias);
                        $html .= is_string($attributeContent) ? $attributeContent : __('The attribute %1 not support show on frontend please choose another attribute.', $alias);
                    endif;
                    if ( !trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            </div>
            <div class="data-tabs-content">
                <?php echo $content ?>
            </div>    
        </div>
    </div>
<?php endif; ?>
