<!-- <head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>
.collapsible {
  background-color: #777;
  color: white;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
}
.collap{position: absolute;}
</style>

</head>
<div class="row bundle-prod margin-vertical longdesc">
<h3 style="margin-left: 15px;">Items included in this bundle</h3>
<div class="bundle-each desc-set" id="product1"><input id="bundleProduct_0" name="bundleProduct[0][]" type="hidden" value="14808-14820"> <input id="bundleProduct_0_quantityBox" name="bundleProduct[0][quantityBox]" type="hidden" value="2">
<div class="col-xs-12 col-sm-12 text-center icon-add margin-bottom bundle-view">
<div class="long-description"><a class="padding-horizontal bundle-tab bundle-box_0" href="#bundle-box_0"> <img id="img_01" src="https://cf-cdn.jihazi.com/public/uploads/catalog/product/small/0/1/01-(1)__2083136114.png"></a>
<div class="dark"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;"> <span style="vertical-align: inherit;">MFI Lightning To Type-C Fast Charging Cable</span></span></span>
<p>SAR99.00</p>
</div>
<div class="specification">
<a id="tab-click0"  class="btn btn-default icon-substract collapsed prod_desc" href="#demo" data-toggle="collapse">VIEW SPECIFICATIONS</a></div>
<div class="panel-collapse collapse" id="demo">
 

<?php
//$_product = $block->getProduct();
//echo $_product = $block->getId();


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    echo $product->getId();
    echo $product->getName();
    echo $product->getSku();
 
//echo $_attributeValue = $block->getProduct()->getResource()->getAttribute('color')->getFrontend()->getValue($block->getProduct());
//echo "1";
//$myAttr = $_product->getResource()->getAttribute('color');

//if ($myAttr){

    // Get Value
  //  $attrValue = $myAttr->getFrontend()->getValue($_product);

    // Get Label
 //   $attrLabel = $myAttr->getStoreLabel();
	
//	echo $attrValue; 
	
//}
?>

</div>
</div>
</div>
</div>
<div class="bundle-each desc-set" id="product2"><input id="bundleProduct_1" name="bundleProduct[1][]" type="hidden" value="14807-14819"> <input id="bundleProduct_1_quantityBox" name="bundleProduct[1][quantityBox]" type="hidden" value="2">
<div class="col-xs-12 col-sm-12 text-center icon-add margin-bottom bundle-view">
<div class="long-description"><a class="padding-horizontal bundle-tab bundle-box_1" href="#bundle-box_1"> <img id="img_01" src="https://cf-cdn.jihazi.com/public/uploads/catalog/product/small/0/1/01__411593180.png"></a>
<div class="dark"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">MFI Lightning Fast Charging Cable</span></span></span>
<p>SAR89.00</p>
</div>
<div class="specification"><a id="tab-click0" class="btn btn-default icon-substract collapsed prod_desc">VIEW SPECIFICATIONS</a></div>
</div>
</div>
</div>
<div class="bundle-each desc-set" id="product3"><input id="bundleProduct_2" name="bundleProduct[2][]" type="hidden" value="14806-14818"> <input id="bundleProduct_2_quantityBox" name="bundleProduct[2][quantityBox]" type="hidden" value="2">
<div class="col-xs-12 col-sm-12 text-center icon-add margin-bottom bundle-view">
<div class="long-description"><a class="padding-horizontal bundle-tab bundle-box_2" href="#bundle-box_2"> <img id="img_01" src="https://cf-cdn.jihazi.com/public/uploads/catalog/product/small/0/1/01-(3)__1566197308.png"></a>
<div class="dark"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">Lectronic Premium TPE Cable Type A-To Micro</span></span></span>
<p>SAR19.00</p>
</div>
<div class="specification"><a id="tab-click0" class="btn btn-default icon-substract collapsed prod_desc">VIEW SPECIFICATIONS</a></div>
</div>
</div>
</div>
<div class="bundle-each desc-set" id="product4"><input id="bundleProduct_3" name="bundleProduct[3][]" type="hidden" value="14805-14817"> <input id="bundleProduct_3_quantityBox" name="bundleProduct[3][quantityBox]" type="hidden" value="2">
<div class="col-xs-12 col-sm-12 text-center icon-add margin-bottom bundle-view">
<div class="long-description"><a class="padding-horizontal bundle-tab bundle-box_3" href="#bundle-box_3"> <img id="img_01" src="https://cf-cdn.jihazi.com/public/uploads/catalog/product/small/0/1/01-(2)__1364643230.png"></a>
<div class="dark"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;"><span style="vertical-align: inherit;">Lectronic Premium TPE Cable Type A-To C</span></span></span>
<p>SAR29.00</p>
</div>
<div class="specification"><a id="tab-click0" class="btn btn-default icon-substract collapsed prod_desc">VIEW SPECIFICATIONS</a></div>
</div>
</div>
</div>
</div>

-->