
<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-07-15 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2020-03-12 21:18:27
 */

/** @var $block \Magento\Catalog\Block\Product\View */

$_product = $block->getProduct();
if ( !$_product->isSaleable() ){
  return;
}
$buttonTitle = __('Add to Cart');
if ($_product->getTypeId() == 'bundle'){
  $buttonTitle = __('Customize and Add to Cart');
}
$helper        = $this->helper('Magepow\Stickycart\Helper\Data');
$aloHelper     = $this->helper('Magiccart\Alothemes\Helper\Data');
$timer         = $aloHelper->getTimer($_product);
$_imageHelper  = $this->helper('Magento\Catalog\Helper\Image');
$heightScroll  = $helper->getHeightScroll();
$widthtImage   = $helper->getWidthImage();
$heightImage   = $helper->getHeightImage();
$imageUrl      = $_imageHelper->init($_product, 'product_base_image')
                ->constrainOnly(TRUE)
                ->keepAspectRatio(TRUE)
                ->keepTransparency(TRUE)
                ->keepFrame(FALSE)
                ->resize($widthtImage, $widthtImage)->getUrl();
?>
<div class="stickyCart">
  <div class="stickyChild">
    <div class="contentHide">
      <div class="clSticky" id="timerSticky">
      <?php if($timer): ?>
        <?php echo $timer; ?>
      <?php else: ?>
        <div class="stickyProductName"><?php echo $block->escapeHtml($_product->getName()) ?></div>
      <?php endif; ?>
      </div>
    </div>
    <div class="contentHide">
      <div class="clSticky">
        <div class="imgBorder">
          <div class="borderImg">
            <img class="stickyImg" src="<?php echo $imageUrl; ?>">
          </div>
        </div>
      </div>
    </div>
    <div class="contentHide">
      <div class="clSticky" id="parentQtySticky">
        <div class="field qty">
          <div class="product-qty">
              <div class="quantity control custom-qty">
                <input  name="qty"
                        type="number" 
                        min="1" 
                        value="<?= $block->getProductDefaultQty() * 1 ?>"
                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                        id="qtySticky"
                        class="input-text qty"
                >
              <div class="btn-plus">
                <button  type="button" class="increase items" onclick="var result = document.getElementById('qtySticky'); var qtySticky = result.value; if( !isNaN( qtySticky )) result.value++;return false;">
                  <i class="fa fa-angle-up"></i>
                </button>
                <button  type="button" class="reduced items" onclick="var result = document.getElementById('qtySticky'); var qtySticky = result.value; if( !isNaN( qtySticky ) && qtySticky > 1 ) result.value--;return false;">
                  <i class="fa fa-angle-down"></i>
                </button>  
              </div> 
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="contentShow">
      <div class="clSticky">
        <button id="btnSticky" class="btn-cart-bottom" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"><span><?= $block->escapeHtml($buttonTitle) ?></span></button>
      </div>
    </div>
  </div>
</div>
<?php
$formData = [
    'stickyCart'                =>  '.stickyCart',
    'qtySticky'                 =>  '#qtySticky',
    'quantity'                  =>  '.quantity',
    'btnSticky'                 =>  '#btnSticky'
];
$stickyData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepowStickycart": {
            "jsonData":<?php /* @noEscape */ echo $stickyData; ?>,
            "typeProduct": "<?php /* @noEscape */ echo $_product->getTypeId(); ?>",
            "scrollHeight": <?php   echo $heightScroll; ?>
            }
        }
    }
</script>