<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$_soldHelper = $this->helper('Magiccart\Alothemes\Helper\Sold');
$timer = $_aloHelper->getTimer($_product);
if(!$timer) return;
?>
<h3 class="slogan-countdown"><?php echo __('Hurry Up!') ?> <span><?php echo __('Special Offers.') ?></span></h3>
<?php
	$sold 	= $_soldHelper->getSoldQty($_product);
	$stockItem = $_product->getExtensionAttributes()->getStockItem();
	$qty 	= (int) $stockItem->getQty();
	$total_sale = $qty + $sold;
	$percent = $qty > 0 ? round(($qty/$total_sale) * 100) : 0;
?>
<div class="product-deal-special-progress">
	<div class="deal-stock-label">
		<span class="stock-available text-left"><?php echo __('Available') ?>: <strong><?php echo $qty ?></strong></span>
		<span class="stock-sold text-right"><?php echo __('Already Sold') ?>: <strong><?php echo $sold ?></strong></span>
	</div>
	<div class="deal-progress">
		<span class="deal-progress-bar" style="width:<?php echo $percent ?>%"><?php echo $percent ?></span>
	</div>
</div>
<?php echo $timer; ?>

