<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap" rel="stylesheet">
<header class="page-header alothemes">
    <div class="header header-sticker">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="header-top-left">
						<div class="welcometop"><?php echo $this->getChildHtml('welcometop'); ?></div>
					</div>
					<div class="header-top-right">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-shop-link')->toHtml();?>
						<div class="header-top-link header-account">
							<div class="toggle-tab">
								<span class="ec ec-user icon-acc"></span>	
								<span><?php echo __("My account")?></span>								
							</div>
							<div class="toggle-content">
								<?php echo $this->getChildHtml('header.links'); ?>
							</div>
						</div>
						<div class="header-top-link">
							<?php echo $this->getChildHtml('store_language'); ?>
							<?php echo $this->getChildHtml('currency'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content menu-mobile">
			<div class="container">
				<div class="row">
					<div class="content-logo">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>	
						<?php //echo $this->getChildHtml('navigation.sections'); ?>						
					</div>
					<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
					<div class="content-seach">
						<div class="search-area header-search">
							<a href="javascript:void(0)" class="search-toggle-icon"><i class="search-icon"></i></a>
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>					
					<div class="righ-header-content">
						<ul class="top-link-product">
							<?php //echo $this->getChildHtml('catalog.compare.link'); ?>
							<li>
								<a title="<?php echo __('Compare') ?>" href="<?php echo $this->getUrl('catalog/product_compare') ?>" target="_blank" class="btn-compare icon icon-compare compare"><i class="ec ec-compare"></i><?php echo __('Compare') ?></a>
							</li>
							<li>
								<a title="<?php echo __('Wishlist') ?>" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="wishlist icon icon-favorites">
							<i class="ec ec-favorites"></i><?php echo __('Wishlist') ?>
								</a>
							</li>
						</ul>
						<?php echo $this->getChildHtml('minicart'); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom">
			<div class="container">
				<div class="row">
					<div class="col-12 col-menu">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
						<?php echo $this->getChildHtml('catalog.topnav'); ?>
						
					</div>
				</div>
					
			</div>
		</div>

	</div>
</header>
<script type="text/javascript">
	require([
		'jquery',
		'magiccart/wow'
        ], function($, init){
        $( document ).ready(function() {
        	new WOW().init();
        });
    });
    require([
        'jquery',
        'magiccart/perfect-scrollbar'
        ], function($,PerfectScrollbar){
        $( document ).ready(function() {
            new PerfectScrollbar('.dd-container');
            
        });
    });
</script>

<?php /*<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$grandTotal = $cart->getQuote()->getGrandTotal();
 if($grandTotal <= 199)
    {?>
        <style>#checkout-shipping-method-load tbody .row:nth-child(1), #checkout-shipping-method-load tbody .row:nth-child(2), #checkout-shipping-method-load tbody .row:nth-child(3), #checkout-shipping-method-load tbody .row:nth-child(4), #checkout-shipping-method-load tbody .row:nth-child(5), #checkout-shipping-method-load tbody .row:nth-child(6){display:none;}
        #co-shipping-method-form .item-title:nth-child(1){display:none;}
        .cart-summary .block .item-options:nth-child(1){display:none;}</style>
    <?php }
?>

<script>
    $('#label_method_OND_aramex').parent('row').addClass('aramexcusom');
</script>
*/ ?>
