<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2016-03-31 10:17:01
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct magiccategory-product autoplay">
<?php
$tabs = $this->getTabs();
$title = $this->getTitle();
$numTabs = count($tabs);
if($numTabs): ?>
    <div class="block-title-tabs clearfix">
    <h3 class="title"><?php echo $title; ?></h3>
    <span class="toggle-tab mobile"><i class="fa fa-bars"></i></span>
	<ul class="magictabs toggle-content" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
	<?php $activated = $this->getTabActivated();
		$limit = $this->getLimit();
		$single = ($numTabs ==1) ? 'single' : '';
		foreach ($tabs as $type => $name):
			$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
			$status .= ($type == $activated) ? " activated $single" : '';
			echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
		endforeach;
	?>
	</ul>
    </div>
<?php endif ?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/category3', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	<div class="box-product-content clearfix">
	    <div class="box-product">
			<div class="content-products" 
			<?php foreach ($this->getFrontendCfg() as $opt) :?>
				data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
			<?php endforeach;?>

			>
			<?php 
				echo $this->getContent('category/grid-multi.phtml');	
			?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
require(['jquery','magiccart/slick','magicproduct']);
</script>
