<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2016-11-01 09:45:16
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct +autoplay">
<div class="row">	
<?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
	if($numTabs): ?>
	    <div class="col-sm-12 col-md-4 col-lg-4 hot-deals-tab-time-col">
		    <div class="block-title-tabs">
		    	<div class="hot-deals-tab-box">
			    	<h2><?php echo __('Hot Deals Products') ?></h2>
					<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
					<?php $activated = $this->getTabActivated();
						$limit = $this->getLimit();
						$single = ($numTabs ==1) ? 'single' : '';
						foreach ($tabs as $type => $name):
							$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
							$status .= ($type == $activated) ? " activated $single" : '';
							echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
						endforeach;
					?>
					</ul>
					<?php 
						$timer  = $this->getData('countdown');
						$timer = $timer ?  date('n/d/Y', strtotime($timer)) : 0;
						if($timer) : 
					?>
						<div class="alo-count-down count-down-time">
							<div class="caption-count">
								<span class="title">Hurry up!</span>
								<span class="letter">Offer ends in:</span>
							</div>
							<div class="countdown caption" data-timer="<?php echo $timer ?>"></div>
						</div>
					<?php endif ?>
				</div>
		    </div>
	    </div>
	<?php endif ?>
		<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/product', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
		<div class="col-sm-12 col-md-8 col-lg-8 hot-deals-tab-content-col">
			<div class="box-product-content clearfix">
				<div class="content-products" 
				<?php foreach ($this->getFrontendCfg() as $opt) :?>
					data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
					data-lazyLoad='progressive'
				<?php endforeach;?>        
				>
				<?php 
					$timer = $this->getTimer();
					if($timer) echo $this->getContent('product/gridtimer.phtml');	
					else echo $this->getContent('product/grid-hotdeals.phtml');	
				?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require([
		'jquery',
		'magiccart/slick',
		'magicproduct'
		], function($, slick, magicproduct){
			$(".<?php echo $selector?>").magicproduct({
				selector : ".<?php echo $selector?>", // Selector product grid
			});
		});
</script>
<!-- <script type="text/javascript">
require(['jquery','magiccart/slick','magicproduct']);
</script> -->

