<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
              <?php 
                        if($customerSession->isLoggedIn()) {
                            echo sprintf(__('Hi, %s'), $customerSession->getCustomer()->getFirstname());
                        } else {
                            echo __('Hello! Sign in'); 
                        }
                    ?>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if($block->getChildHtml()):?>        
        <div class="customer-menu" data-target="dropdown">
            <?= $block->getChildHtml() ?>           
        </div>
        <?php endif; ?>
    </li>
<?php endif; ?>
